# Generated by Django 5.1.7 on 2025-03-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("post_time", models.DateTimeField()),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BA", "Bosnia and Herzegovina"),
                            ("HR", "Croatia"),
                            ("RS", "Serbia"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
            ],
        ),
    ]
