# Generated by Django 5.1.7 on 2025-03-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="post_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
