# Generated by Django 5.1.7 on 2025-03-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0002_alter_news_post_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "verbose_name": "News Article",
                "verbose_name_plural": "News Articles",
            },
        ),
    ]
