# Generated by Django 5.1.7 on 2025-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='country',
            field=models.CharField(blank=True, choices=[('ba', 'Bosnia and Herzegovina'), ('hr', 'Croatia'), ('rs', 'Serbia')], max_length=2, null=True),
        ),
    ]
