# Generated by Django 5.2 on 2025-04-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_category_alter_news_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
