# Generated by Django 5.2 on 2025-05-21 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_alter_category_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='long_summary',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_summary',
        ),
    ]
